package br.sp.puc.camel.model.visa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-12-04T23:19:22.048-02:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "SolicitarPagamento", 
                  wsdlLocation = "file:/home/gabriel/projects/secret-octo-meme/src/main/resources/META-INF/wsdl/SolicitarPagamentoVisa.wsdl",
                  targetNamespace = "http://ws.apache.org/axis2") 
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00", comments = "Apache CXF 3.0.1")
public class SolicitarPagamento_Service extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public final static QName SERVICE = new QName("http://ws.apache.org/axis2", "SolicitarPagamento");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public final static QName SolicitarPagamentoHttpSoap12Endpoint = new QName("http://ws.apache.org/axis2", "SolicitarPagamentoHttpSoap12Endpoint");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public final static QName SolicitarPagamentoHttpSoap11Endpoint = new QName("http://ws.apache.org/axis2", "SolicitarPagamentoHttpSoap11Endpoint");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public final static QName SolicitarPagamentoHttpEndpoint = new QName("http://ws.apache.org/axis2", "SolicitarPagamentoHttpEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/gabriel/projects/secret-octo-meme/src/main/resources/META-INF/wsdl/SolicitarPagamentoVisa.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SolicitarPagamento_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/gabriel/projects/secret-octo-meme/src/main/resources/META-INF/wsdl/SolicitarPagamentoVisa.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamento_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamento_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamento_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamento_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamento_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamento_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SolicitarPagamentoPortType
     */
    @WebEndpoint(name = "SolicitarPagamentoHttpSoap12Endpoint")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamentoPortType getSolicitarPagamentoHttpSoap12Endpoint() {
        return super.getPort(SolicitarPagamentoHttpSoap12Endpoint, SolicitarPagamentoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolicitarPagamentoPortType
     */
    @WebEndpoint(name = "SolicitarPagamentoHttpSoap12Endpoint")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamentoPortType getSolicitarPagamentoHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(SolicitarPagamentoHttpSoap12Endpoint, SolicitarPagamentoPortType.class, features);
    }
    /**
     *
     * @return
     *     returns SolicitarPagamentoPortType
     */
    @WebEndpoint(name = "SolicitarPagamentoHttpSoap11Endpoint")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamentoPortType getSolicitarPagamentoHttpSoap11Endpoint() {
        return super.getPort(SolicitarPagamentoHttpSoap11Endpoint, SolicitarPagamentoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolicitarPagamentoPortType
     */
    @WebEndpoint(name = "SolicitarPagamentoHttpSoap11Endpoint")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamentoPortType getSolicitarPagamentoHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(SolicitarPagamentoHttpSoap11Endpoint, SolicitarPagamentoPortType.class, features);
    }
    /**
     *
     * @return
     *     returns SolicitarPagamentoPortType
     */
    @WebEndpoint(name = "SolicitarPagamentoHttpEndpoint")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamentoPortType getSolicitarPagamentoHttpEndpoint() {
        return super.getPort(SolicitarPagamentoHttpEndpoint, SolicitarPagamentoPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolicitarPagamentoPortType
     */
    @WebEndpoint(name = "SolicitarPagamentoHttpEndpoint")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.048-02:00")
    public SolicitarPagamentoPortType getSolicitarPagamentoHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(SolicitarPagamentoHttpEndpoint, SolicitarPagamentoPortType.class, features);
    }

}
