package br.sp.puc.camel.model.visa;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-12-04T23:19:22.016-02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://ws.apache.org/axis2", name = "SolicitarPagamentoPortType")
@XmlSeeAlso({br.com.gpvisa.model.xsd.ObjectFactory.class, ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.016-02:00", comments = "Apache CXF 3.0.1")
public interface SolicitarPagamentoPortType {

    @WebResult(name = "return", targetNamespace = "http://ws.apache.org/axis2")
    @Action(input = "urn:solicitarPagamento", output = "urn:solicitarPagamentoResponse")
    @RequestWrapper(localName = "solicitarPagamento", targetNamespace = "http://ws.apache.org/axis2", className = "org.apache.ws.axis2.SolicitarPagamento")
    @WebMethod(action = "urn:solicitarPagamento")
    @ResponseWrapper(localName = "solicitarPagamentoResponse", targetNamespace = "http://ws.apache.org/axis2", className = "org.apache.ws.axis2.SolicitarPagamentoResponse")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-04T23:19:22.016-02:00")
    public br.com.gpvisa.model.xsd.MensagemTO solicitarPagamento(
        @WebParam(name = "pedido", targetNamespace = "http://ws.apache.org/axis2")
        java.lang.Integer pedido,
        @WebParam(name = "cliente", targetNamespace = "http://ws.apache.org/axis2")
        java.lang.String cliente,
        @WebParam(name = "valor", targetNamespace = "http://ws.apache.org/axis2")
        java.lang.Double valor,
        @WebParam(name = "numeroCartao", targetNamespace = "http://ws.apache.org/axis2")
        java.lang.String numeroCartao
    );
}
