package br.sp.puc.camel.model;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-12-05T01:35:40.617-02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://br.sp.puc/services/pagamento", name = "SolicitarPagamento")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-05T01:35:40.617-02:00", comments = "Apache CXF 3.0.1")
public interface SolicitarPagamento {

    @WebMethod
    @WebResult(name = "solicitarPagamentoResponse", targetNamespace = "http://br.sp.puc/services/pagamento", partName = "out")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2014-12-05T01:35:40.617-02:00")
    public SolicitarPagamentoResponse solicitarPagamento(
            @WebParam(partName = "in", name = "solicitarPagamentoRequest", targetNamespace = "http://br.sp.puc/services/pagamento")
            SolicitarPagamentoRequest in
    );
}
